-- Add Admins
INSERT INTO USERS (EMAIL, NAME, PASSWORD, ROLE)
VALUES ('milan@imf.com', 'Milan', 1234, 'ADMIN');
INSERT INTO USERS (EMAIL, NAME, PASSWORD, ROLE)
VALUES ('mark@imf.com', 'Mark', 1234, 'ADMIN');
INSERT INTO USERS (EMAIL, NAME, PASSWORD, ROLE)
VALUES ('malnin@imf.com', 'Malni', 1234, 'ADMIN');
